### ISSUE TITLE
Unable to install kubectl krew clusternet in local server

### ISSUE THREAD

**Issue by shekhar250723** [clusternet/kubectl-clusternet#12]
kubectl clusternet version (no status found)

**C:\Users\INILPTP087>kubectl clusternet version
Error: unknown command "clusternet" for "kubectl"**

Following this link
https://clusternet.io/docs/tutorials/cluster-management/visiting-child-clusters-with-rbac/visit-child-clusters-with-kubectl-clusternet/

#### Environment:
- kubectl clusternet plugin version(use `kubectl clusternet version` or `kubectl-clusternet version`):
- Kubectl version (use `kubectl version --client`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by dixudx** [comment]
@shekhar250723 You're using Windows. Please try to follow [krew installation on Windows](https://krew.sigs.k8s.io/docs/user-guide/setup/install/#windows).

**Comment by shekhar250723** [comment]
@dixudx I tried to follow the same link and downloaded the krew.exe file and provided the system variable path in local machine.

Now, tried to run below command but getting error

**C:\Windows\System32>.\krew install krew
'.\krew' is not recognized as an internal or external command,
operable program or batch file.**

**Comment by dixudx** [comment]
Would you please try [5 Ways to Fix the "Not Recognized as an Internal or External Command" Error in Windows](https://www.makeuseof.com/windows-not-recognized-as-an-internal-or-external-command-error/)? Please try to find a way to solve that.

This is purely a Windows issue. This has nothing to do with `krew` or `clusternet`.

**Comment by shekhar250723** [comment]
@dixudx I have done all the steps but it doesn't help me.

Could you please provide simple steps to resolve this issue?

**Comment by dixudx** [comment]
@shekhar250723 This is purely a Windows itself issue. It has nothing to do with krew or clusternet. I think you can try to see whether `.\\krew install krew` works.

Also please try to solve this problem by searching on Google and find feasible ways to solve this by yourself. I am not running on Windows. Sorry, I cannot provide any detailed steps to help you. This is purely a Windows itself issue.

**Comment by shekhar250723** [comment]
@dixudx Now, we are getting error in below link
https://clusternet.io/docs/tutorials/service-management/visting-services-child-cluster-port-forward/

Unable to check my-ngnix test status through below command only kubernetes status is visible but on the shared link both status are visible. Please support on this.

a@INILPTP087:~$ kubectl clusternet get svc --cluster-id=20ef8c64-5f25-4ea2-ad49-60ed82db47d8 --kubeconfig=.kube/config
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.68.0.1    <none>        443/TCP   5d6h

So getting error in step number 3rd
a@INILPTP087:~$ kubectl clusternet port-forward --namespace default --cluster-id=20ef8c64-5f25-4ea2-ad49-60ed82db47d8 --kubeconfig=.kube/config svc/my-nginx-test 8080:80
Error from server (NotFound): services "my-nginx-test" not found

**Comment by dixudx** [comment]
@shekhar250723 In doc https://clusternet.io/docs/tutorials/service-management/visting-services-child-cluster-port-forward/, there shows a flag `--child-kubeconifg`, which is required when accessing child clusters. Currently you're ignore it. Please add it, then retry.

- `--kubeconfig` specifies the kubeconfig of parent cluster
- `--child-kubeconfig` specifies the kubeconfig of a certain child cluster

**Comment by shekhar250723** [comment]
@dixudx How can I setup it in child clusters? I didn't get any step for the same.

**Comment by dixudx** [comment]
> How can I setup it in child clusters? I didn't get any step for the same.

This does not need any extra setup. When you create/install a Kubernetes cluster, you should have got kubeconfig files.

Clusternet does not help create your clusters. You can have multiple ways to create a Kubernetes cluster. Clusternet just manages those clusters.

If we need to access a Kubernetes cluster, we need to have a kubeconfig, right? Now we're trying to access a child cluster via parent cluster endpoint. So just pass the child cluster kubeconfig via flag `--child-kubeconfig`. That's it.

**Comment by shekhar250723** [comment]
@dixudx I can check the below status in --child-kubeconfig. But how can I manage child cluster through parent cluster. Need your support on this.

```
     server: https://34.31.127.125
  name: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
contexts:
- context:
    cluster: gke_dulcet-clock-393808_us-central1-c_clusternet-child
    user: gke_dulcet-clock-393808_us-central1-c_clusternet-child
  name: gke_dulcet-clock-393808_us-central1-c_clusternet-child
- context:
    cluster: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
    user: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
  name: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
current-context: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
kind: Config
preferences: {}
users:
- name: gke_dulcet-clock-393808_us-central1-c_clusternet-child
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      interactiveMode: IfAvailable
      provideClusterInfo: true
- name: gke_dulcet-clock-393808_us-central1-c_clusternet-parent
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      interactiveMode: IfAvailable
      provideClusterInfo: true
```
